name: location_tracking_app
description: "A Flutter application for location and data tracking."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Existing dependencies
  get: ^4.6.6
  permission_handler: ^11.3.1
  intl: ^0.19.0
  location: ^6.0.2

  # New dependency for showing toasts
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
